APP_TITLE    := Ultimate Spider-Man: Total Mayhem HD
APP_AUTHOR   := Homebrew wrapper
APP_VERSION  := 0.0.1-stage0
TARGET       := spiderman_total_mayhem_nx
PORT_PAYLOAD := spiderman_tm_nx
TOPDIR ?= $(CURDIR)
A32    ?= $(TOPDIR)/../runtime
include $(A32)/launcher/launcher.mk
