/* imports.c -- GENERATED by runtime/tools/gen_imports.py; do not edit.
 *
 * Every import of libspiderman that no loaded module
 * exports (gl* aside: the GL layer serves those), mapped to the host
 * function or object that serves it: b_* shims for the bionic ABI
 * (bionic_*.c, android_ndk.c, gl_*.c, the port's files), and newlib
 * directly where the two ABIs agree. Declared through asm labels so no
 * C prototype is needed (or can conflict): only the address is taken
 * here. The search over the table is the runtime's imports_lookup.c.
 *
 * Weak imports bound to NULL on purpose: none.
 * MIT.
 */
#include "imports.h"

extern const char sym___aeabi_d2f[] __asm__("__aeabi_d2f");
extern const char sym___aeabi_d2iz[] __asm__("__aeabi_d2iz");
extern const char sym___aeabi_d2uiz[] __asm__("__aeabi_d2uiz");
extern const char sym___aeabi_dadd[] __asm__("__aeabi_dadd");
extern const char sym___aeabi_dcmpeq[] __asm__("__aeabi_dcmpeq");
extern const char sym___aeabi_dcmpge[] __asm__("__aeabi_dcmpge");
extern const char sym___aeabi_dcmpgt[] __asm__("__aeabi_dcmpgt");
extern const char sym___aeabi_dcmple[] __asm__("__aeabi_dcmple");
extern const char sym___aeabi_dcmplt[] __asm__("__aeabi_dcmplt");
extern const char sym___aeabi_ddiv[] __asm__("__aeabi_ddiv");
extern const char sym___aeabi_dmul[] __asm__("__aeabi_dmul");
extern const char sym___aeabi_dsub[] __asm__("__aeabi_dsub");
extern const char sym___aeabi_f2d[] __asm__("__aeabi_f2d");
extern const char sym___aeabi_f2iz[] __asm__("__aeabi_f2iz");
extern const char sym___aeabi_fadd[] __asm__("__aeabi_fadd");
extern const char sym___aeabi_fcmpeq[] __asm__("__aeabi_fcmpeq");
extern const char sym___aeabi_fcmpge[] __asm__("__aeabi_fcmpge");
extern const char sym___aeabi_fcmpgt[] __asm__("__aeabi_fcmpgt");
extern const char sym___aeabi_fcmple[] __asm__("__aeabi_fcmple");
extern const char sym___aeabi_fcmplt[] __asm__("__aeabi_fcmplt");
extern const char sym___aeabi_fcmpun[] __asm__("__aeabi_fcmpun");
extern const char sym___aeabi_fdiv[] __asm__("__aeabi_fdiv");
extern const char sym___aeabi_fmul[] __asm__("__aeabi_fmul");
extern const char sym___aeabi_fsub[] __asm__("__aeabi_fsub");
extern const char sym___aeabi_i2d[] __asm__("__aeabi_i2d");
extern const char sym___aeabi_i2f[] __asm__("__aeabi_i2f");
extern const char sym___aeabi_idiv[] __asm__("__aeabi_idiv");
extern const char sym___aeabi_idivmod[] __asm__("__aeabi_idivmod");
extern const char sym___aeabi_ldivmod[] __asm__("__aeabi_ldivmod");
extern const char sym___aeabi_lmul[] __asm__("__aeabi_lmul");
extern const char sym___aeabi_ui2d[] __asm__("__aeabi_ui2d");
extern const char sym___aeabi_ui2f[] __asm__("__aeabi_ui2f");
extern const char sym___aeabi_uidiv[] __asm__("__aeabi_uidiv");
extern const char sym___aeabi_uidivmod[] __asm__("__aeabi_uidivmod");
extern const char sym___aeabi_unwind_cpp_pr0[] __asm__("__aeabi_unwind_cpp_pr0");
extern const char sym___aeabi_unwind_cpp_pr1[] __asm__("__aeabi_unwind_cpp_pr1");
extern const char sym___dso_handle[] __asm__("__dso_handle");
extern const char sym_acos[] __asm__("acos");
extern const char sym_acosf[] __asm__("acosf");
extern const char sym_asin[] __asm__("asin");
extern const char sym_asinf[] __asm__("asinf");
extern const char sym_atan[] __asm__("atan");
extern const char sym_atan2[] __asm__("atan2");
extern const char sym_atan2f[] __asm__("atan2f");
extern const char sym_atanf[] __asm__("atanf");
extern const char sym_atoi[] __asm__("atoi");
extern const char sym_b___aeabi_atexit[] __asm__("b___aeabi_atexit");
extern const char sym_b___android_log_write[] __asm__("b___android_log_write");
extern const char sym_b___cxa_guard_acquire[] __asm__("b___cxa_guard_acquire");
extern const char sym_b___cxa_guard_release[] __asm__("b___cxa_guard_release");
extern const char sym_b___cxa_pure_virtual[] __asm__("b___cxa_pure_virtual");
extern const char sym_b___sF[] __asm__("b___sF");
extern const char sym_b___stack_chk_fail[] __asm__("b___stack_chk_fail");
extern const char sym_b___stack_chk_guard[] __asm__("b___stack_chk_guard");
extern const char sym_b_abort[] __asm__("b_abort");
extern const char sym_b_ceilf[] __asm__("b_ceilf");
extern const char sym_b_chdir[] __asm__("b_chdir");
extern const char sym_b_close[] __asm__("b_close");
extern const char sym_b_connect[] __asm__("b_connect");
extern const char sym_b_exit[] __asm__("b_exit");
extern const char sym_b_fclose[] __asm__("b_fclose");
extern const char sym_b_fgetc[] __asm__("b_fgetc");
extern const char sym_b_floor[] __asm__("b_floor");
extern const char sym_b_floorf[] __asm__("b_floorf");
extern const char sym_b_fopen[] __asm__("b_fopen");
extern const char sym_b_fprintf[] __asm__("b_fprintf");
extern const char sym_b_fread[] __asm__("b_fread");
extern const char sym_b_fseek[] __asm__("b_fseek");
extern const char sym_b_ftell[] __asm__("b_ftell");
extern const char sym_b_fwrite[] __asm__("b_fwrite");
extern const char sym_b_gethostbyname[] __asm__("b_gethostbyname");
extern const char sym_b_gettimeofday[] __asm__("b_gettimeofday");
extern const char sym_b_memcpy[] __asm__("b_memcpy");
extern const char sym_b_memmove[] __asm__("b_memmove");
extern const char sym_b_memset[] __asm__("b_memset");
extern const char sym_b_nanosleep[] __asm__("b_nanosleep");
extern const char sym_b_printf[] __asm__("b_printf");
extern const char sym_b_puts[] __asm__("b_puts");
extern const char sym_b_recv[] __asm__("b_recv");
extern const char sym_b_remove[] __asm__("b_remove");
extern const char sym_b_rename[] __asm__("b_rename");
extern const char sym_b_snprintf[] __asm__("b_snprintf");
extern const char sym_b_socket[] __asm__("b_socket");
extern const char sym_b_sprintf[] __asm__("b_sprintf");
extern const char sym_b_sqrt[] __asm__("b_sqrt");
extern const char sym_b_sqrtf[] __asm__("b_sqrtf");
extern const char sym_b_uname[] __asm__("b_uname");
extern const char sym_b_vsprintf[] __asm__("b_vsprintf");
extern const char sym_b_write[] __asm__("b_write");
extern const char sym_cos[] __asm__("cos");
extern const char sym_cosf[] __asm__("cosf");
extern const char sym_expf[] __asm__("expf");
extern const char sym_fmod[] __asm__("fmod");
extern const char sym_fmodf[] __asm__("fmodf");
extern const char sym_free[] __asm__("free");
extern const char sym_logf[] __asm__("logf");
extern const char sym_lrand48[] __asm__("lrand48");
extern const char sym_malloc[] __asm__("malloc");
extern const char sym_memcmp[] __asm__("memcmp");
extern const char sym_pow[] __asm__("pow");
extern const char sym_powf[] __asm__("powf");
extern const char sym_sin[] __asm__("sin");
extern const char sym_sinf[] __asm__("sinf");
extern const char sym_srand48[] __asm__("srand48");
extern const char sym_sscanf[] __asm__("sscanf");
extern const char sym_strcasecmp[] __asm__("strcasecmp");
extern const char sym_strcat[] __asm__("strcat");
extern const char sym_strchr[] __asm__("strchr");
extern const char sym_strcmp[] __asm__("strcmp");
extern const char sym_strcpy[] __asm__("strcpy");
extern const char sym_strdup[] __asm__("strdup");
extern const char sym_strlen[] __asm__("strlen");
extern const char sym_strncmp[] __asm__("strncmp");
extern const char sym_strpbrk[] __asm__("strpbrk");
extern const char sym_strstr[] __asm__("strstr");
extern const char sym_strtod[] __asm__("strtod");
extern const char sym_tan[] __asm__("tan");
extern const char sym_tanf[] __asm__("tanf");
extern const char sym_wcscmp[] __asm__("wcscmp");
extern const char sym_wcscpy[] __asm__("wcscpy");
extern const char sym_wcslen[] __asm__("wcslen");

DynLibFunction dcr_imports[] = {
    {"__aeabi_atexit", (uintptr_t)sym_b___aeabi_atexit},
    {"__aeabi_d2f", (uintptr_t)sym___aeabi_d2f},
    {"__aeabi_d2iz", (uintptr_t)sym___aeabi_d2iz},
    {"__aeabi_d2uiz", (uintptr_t)sym___aeabi_d2uiz},
    {"__aeabi_dadd", (uintptr_t)sym___aeabi_dadd},
    {"__aeabi_dcmpeq", (uintptr_t)sym___aeabi_dcmpeq},
    {"__aeabi_dcmpge", (uintptr_t)sym___aeabi_dcmpge},
    {"__aeabi_dcmpgt", (uintptr_t)sym___aeabi_dcmpgt},
    {"__aeabi_dcmple", (uintptr_t)sym___aeabi_dcmple},
    {"__aeabi_dcmplt", (uintptr_t)sym___aeabi_dcmplt},
    {"__aeabi_ddiv", (uintptr_t)sym___aeabi_ddiv},
    {"__aeabi_dmul", (uintptr_t)sym___aeabi_dmul},
    {"__aeabi_dsub", (uintptr_t)sym___aeabi_dsub},
    {"__aeabi_f2d", (uintptr_t)sym___aeabi_f2d},
    {"__aeabi_f2iz", (uintptr_t)sym___aeabi_f2iz},
    {"__aeabi_fadd", (uintptr_t)sym___aeabi_fadd},
    {"__aeabi_fcmpeq", (uintptr_t)sym___aeabi_fcmpeq},
    {"__aeabi_fcmpge", (uintptr_t)sym___aeabi_fcmpge},
    {"__aeabi_fcmpgt", (uintptr_t)sym___aeabi_fcmpgt},
    {"__aeabi_fcmple", (uintptr_t)sym___aeabi_fcmple},
    {"__aeabi_fcmplt", (uintptr_t)sym___aeabi_fcmplt},
    {"__aeabi_fcmpun", (uintptr_t)sym___aeabi_fcmpun},
    {"__aeabi_fdiv", (uintptr_t)sym___aeabi_fdiv},
    {"__aeabi_fmul", (uintptr_t)sym___aeabi_fmul},
    {"__aeabi_fsub", (uintptr_t)sym___aeabi_fsub},
    {"__aeabi_i2d", (uintptr_t)sym___aeabi_i2d},
    {"__aeabi_i2f", (uintptr_t)sym___aeabi_i2f},
    {"__aeabi_idiv", (uintptr_t)sym___aeabi_idiv},
    {"__aeabi_idivmod", (uintptr_t)sym___aeabi_idivmod},
    {"__aeabi_ldivmod", (uintptr_t)sym___aeabi_ldivmod},
    {"__aeabi_lmul", (uintptr_t)sym___aeabi_lmul},
    {"__aeabi_ui2d", (uintptr_t)sym___aeabi_ui2d},
    {"__aeabi_ui2f", (uintptr_t)sym___aeabi_ui2f},
    {"__aeabi_uidiv", (uintptr_t)sym___aeabi_uidiv},
    {"__aeabi_uidivmod", (uintptr_t)sym___aeabi_uidivmod},
    {"__aeabi_unwind_cpp_pr0", (uintptr_t)sym___aeabi_unwind_cpp_pr0},
    {"__aeabi_unwind_cpp_pr1", (uintptr_t)sym___aeabi_unwind_cpp_pr1},
    {"__android_log_write", (uintptr_t)sym_b___android_log_write},
    {"__cxa_guard_acquire", (uintptr_t)sym_b___cxa_guard_acquire},
    {"__cxa_guard_release", (uintptr_t)sym_b___cxa_guard_release},
    {"__cxa_pure_virtual", (uintptr_t)sym_b___cxa_pure_virtual},
    {"__dso_handle", (uintptr_t)sym___dso_handle},
    {"__sF", (uintptr_t)sym_b___sF},
    {"__stack_chk_fail", (uintptr_t)sym_b___stack_chk_fail},
    {"__stack_chk_guard", (uintptr_t)sym_b___stack_chk_guard},
    {"abort", (uintptr_t)sym_b_abort},
    {"acos", (uintptr_t)sym_acos},
    {"acosf", (uintptr_t)sym_acosf},
    {"asin", (uintptr_t)sym_asin},
    {"asinf", (uintptr_t)sym_asinf},
    {"atan", (uintptr_t)sym_atan},
    {"atan2", (uintptr_t)sym_atan2},
    {"atan2f", (uintptr_t)sym_atan2f},
    {"atanf", (uintptr_t)sym_atanf},
    {"atoi", (uintptr_t)sym_atoi},
    {"ceilf", (uintptr_t)sym_b_ceilf},
    {"chdir", (uintptr_t)sym_b_chdir},
    {"close", (uintptr_t)sym_b_close},
    {"connect", (uintptr_t)sym_b_connect},
    {"cos", (uintptr_t)sym_cos},
    {"cosf", (uintptr_t)sym_cosf},
    {"exit", (uintptr_t)sym_b_exit},
    {"expf", (uintptr_t)sym_expf},
    {"fclose", (uintptr_t)sym_b_fclose},
    {"fgetc", (uintptr_t)sym_b_fgetc},
    {"floor", (uintptr_t)sym_b_floor},
    {"floorf", (uintptr_t)sym_b_floorf},
    {"fmod", (uintptr_t)sym_fmod},
    {"fmodf", (uintptr_t)sym_fmodf},
    {"fopen", (uintptr_t)sym_b_fopen},
    {"fprintf", (uintptr_t)sym_b_fprintf},
    {"fread", (uintptr_t)sym_b_fread},
    {"free", (uintptr_t)sym_free},
    {"fseek", (uintptr_t)sym_b_fseek},
    {"ftell", (uintptr_t)sym_b_ftell},
    {"fwrite", (uintptr_t)sym_b_fwrite},
    {"gethostbyname", (uintptr_t)sym_b_gethostbyname},
    {"gettimeofday", (uintptr_t)sym_b_gettimeofday},
    {"logf", (uintptr_t)sym_logf},
    {"lrand48", (uintptr_t)sym_lrand48},
    {"malloc", (uintptr_t)sym_malloc},
    {"memcmp", (uintptr_t)sym_memcmp},
    {"memcpy", (uintptr_t)sym_b_memcpy},
    {"memmove", (uintptr_t)sym_b_memmove},
    {"memset", (uintptr_t)sym_b_memset},
    {"nanosleep", (uintptr_t)sym_b_nanosleep},
    {"pow", (uintptr_t)sym_pow},
    {"powf", (uintptr_t)sym_powf},
    {"printf", (uintptr_t)sym_b_printf},
    {"puts", (uintptr_t)sym_b_puts},
    {"recv", (uintptr_t)sym_b_recv},
    {"remove", (uintptr_t)sym_b_remove},
    {"rename", (uintptr_t)sym_b_rename},
    {"sin", (uintptr_t)sym_sin},
    {"sinf", (uintptr_t)sym_sinf},
    {"snprintf", (uintptr_t)sym_b_snprintf},
    {"socket", (uintptr_t)sym_b_socket},
    {"sprintf", (uintptr_t)sym_b_sprintf},
    {"sqrt", (uintptr_t)sym_b_sqrt},
    {"sqrtf", (uintptr_t)sym_b_sqrtf},
    {"srand48", (uintptr_t)sym_srand48},
    {"sscanf", (uintptr_t)sym_sscanf},
    {"strcasecmp", (uintptr_t)sym_strcasecmp},
    {"strcat", (uintptr_t)sym_strcat},
    {"strchr", (uintptr_t)sym_strchr},
    {"strcmp", (uintptr_t)sym_strcmp},
    {"strcpy", (uintptr_t)sym_strcpy},
    {"strdup", (uintptr_t)sym_strdup},
    {"strlen", (uintptr_t)sym_strlen},
    {"strncmp", (uintptr_t)sym_strncmp},
    {"strpbrk", (uintptr_t)sym_strpbrk},
    {"strstr", (uintptr_t)sym_strstr},
    {"strtod", (uintptr_t)sym_strtod},
    {"tan", (uintptr_t)sym_tan},
    {"tanf", (uintptr_t)sym_tanf},
    {"uname", (uintptr_t)sym_b_uname},
    {"vsprintf", (uintptr_t)sym_b_vsprintf},
    {"wcscmp", (uintptr_t)sym_wcscmp},
    {"wcscpy", (uintptr_t)sym_wcscpy},
    {"wcslen", (uintptr_t)sym_wcslen},
    {"write", (uintptr_t)sym_b_write},
    {"", 0},
};

int dcr_imports_count = (int)(sizeof(dcr_imports) / sizeof(dcr_imports[0])) - 1;
